name: Sync to Hugging Face Hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      # Add Hugging Face as a remote
      - name: Add Hugging Face remote
        run: git remote add hf https://ailab-bio:$HF_TOKEN@huggingface.co/spaces/ailab-bio/PROTAC-Degradation-Predictor

      # Pull changes from Hugging Face before pushing
      - name: Pull from Hugging Face
        run: git pull hf main --allow-unrelated-histories

      # Push changes to Hugging Face after resolving any conflicts
      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push hf main
